### ISSUE TITLE
Multi-core building

### ISSUE THREAD

**Issue by yobson** [fedora-haskell/ghc-rpm-macros#10]
Hello!

I don't know how the other RPM projects use these macros, but in openSUSE, all of the dependencies are prebuilt and packaged as RPMs. For this reason, it would make sense to pass:
 `--ghc-option=-j[N]`
to utilise `[N]` of the build cores available.

Would it be possible to add it, or is there a good reason that it isn't passed?

**Comment by juhp** [comment]
Thanks for the question: btw it is not well documented but this repo is really in archive mode (though not so obvious).

I believe opensuse is currently using its own fork, but I could be mistaken.

Ah you want to enable parallel builds in Cabal I think, I see: that is an interesting idea.

**Comment by yobson** [comment]
I'll try find their fork and take it up with them!

Thanks. I think it would be a relatively simple change (famous last words) but I'm not that knowledgable with RPM macros

I'll close the issue given the archived state of this repo

**Comment by juhp** [comment]
Yes it should be.

I think (you can see) I add `%{?ghc_smp_mflags}` here long ago but seemed to have forgotten about it (it is not defined by default). It could indeed speed builds a fair bit.
So thanks for the suggestion: I will start by adding it to Fedora.

If `%{?ghc_smp_mflags}` is there in the opensuse package you can try defining it locally first even to test it out.

Also had loose plans to make this repo the official upstream (at least for Fedora) someday.
