### ISSUE TITLE
ghc-pkg-wrapper in libexecdir 

### ISSUE THREAD

**Issue by mimi1vx** [fedora-haskell/ghc-rpm-macros#2]
Hello, 

we have small problem with 'ghc-pkg-wrapper' in  /usr/libexec which isn't supported in SUSE and openSUSE

Plus badly generates Requires: in rpm:(

**Comment by juhp** [comment]
Do you have an alternative to libexec?

> Plus badly generates Requires: in rpm:(

Could you explain more?

**Comment by mimi1vx** [comment]
no, opensuse relays on older FHS, whithout defined libexec, --> all executable files to /usr/bin or /bin

for second issue:  "echo $files | tr [:blank:] '\n' | /usr/lib/rpm/rpmdeps --requires" in ghc-deps.sh  fixes it, but its multiply needed RAM for build simply packages..

Please compare:

https://build.opensuse.org/package/statistics/home:mimi_vx:ghc-rpm/ghc-text?arch=x86_64&repository=SLE_12

with 

https://build.opensuse.org/package/statistics/devel:languages:haskell/ghc-text?arch=x86_64&repository=SLE_12

**Comment by mimi1vx** [comment]
Plus why is ghc-deps.sh splitted to two files ?

**Comment by juhp** [comment]
I think I fixed your second issue yesterday with commit bf28f3569.

ghc-pkg-wrapper is used by both `ghc-dep.sh` and `macros.ghc`.
I guess I could put it under `/usr/lib/rpm/` then.

(I never really understood why FHS can't adopt libexec but that is another story I suppose.)

**Comment by juhp** [comment]
Thanks for the report and more feedback is welcome.
