### ISSUE TITLE
Take advantage of multi-core systems when building

### ISSUE THREAD

**Issue by peti** [fedora-haskell/ghc-rpm-macros#4]
The `Setup build` phase should be run with with the `-j` flag specified so that GHC takes advantage of multi-core systems. It might be possible to re-use `%{_smp_mflags}` for that purpose. I'm not sure though; that define might contain make-specific flags other than `-j` and might not be suitable for our purposes.

Cc: @mimi1vx

**Comment by juhp** [comment]
I think `%{_smp_mflags}` should work, if not we can try to tweak it.

However build -j is only available for Cabal-1.22+(?) I think.
Maybe it is better to add -j to cabal-rpm even?
(Personally I don't like `-j` because it tends to use too much cpu/memory on my machine so I set `%_smp_ncpus_max 1` in `~/.rpmmacros` etc.)

**Comment by peti** [comment]
`-j` is supported since GHC 7.8.x, which ships Cabal 1.18.x.

**Comment by juhp** [comment]
I know but Cabal 1.18 does not support it AFAIK.

Perhaps we can make the code conditional on the Cabal version.

**Comment by juhp** [comment]
Anyway sorry my comment about Cabal version is kind if irrelevant (actually I was slightly confusing with cabal-rpm) since the macros here currently target ghc-7.10+... and don't work with ghc-7.8 anyway.
(Though generally I am keen to make ghc-rpm-macros more backwards compatible where possible.)

**Comment by juhp** [comment]
I haven't tested it yet - if you can that would be appreciated. :)

**Comment by peti** [comment]
@mimi1vx, can we just update our copy in `devel:languages:haskell:lts-6`  to the latest version of the macros? Shouldn't do any harm, right?

**Comment by mimi1vx** [comment]
@peti  ok, i try prepare new opensuse version, but in `devel:languages:haskell:lts:next`

**Comment by mimi1vx** [comment]
@juhp against ghc-8.0.1 works like charm, plus build speed is increased highly
