### ISSUE TITLE
built fail because LICENSE does not end in %{buildroot}%{ghc_pkgdocdir}

### ISSUE THREAD

**Issue by romanofski** [fedora-haskell/ghc-rpm-macros#5]
Package spec files generated by cabal-rpm have an install line:

    rm %{buildroot}%{ghc_pkgdocdir}/LICENSE

which fails with the following error message during the installation step:

    rm: cannot remove '/builddir/build/BUILDROOT/ghc-ini-0.3.4-1.fc25.x86_64/usr/share/doc/ghc-ini/LICENSE': No such file or directory

I think, the problem is, configure installs the LICENSE to a different directory:

    %{?_defaultlicensedir}%{!?_defaultlicensedir:%_docdir}/%{name}

but I'm not really sure, since I'm new to packaging. Maybe it is a problem in cabal-rpm, not in ghc-rpm-macros or simply with me using the wrong macros?

PS: Attaching the build.log.gz which is quite small to help debugging the problem.
[build.log.gz](https://github.com/fedora-haskell/ghc-rpm-macros/files/753588/build.log.gz)

**Comment by juhp** [comment]
Oops, blush dunno how I didn't see this report earlier sorry.
Do you still see this problem with current cabal-rpm etc?
(I suspect it may well be fixed.)

**Comment by romanofski** [comment]
@juhp No worries. I haven't tried for a while. Let me try a new build and see how it goes.

**Comment by romanofski** [comment]
@juhp I've tried it and the problem seems to have been fixed in the mean time :) Cheers!
